#!/usr/bin/env python3
"""Regenerate C++ tables under src/core/ from the local matplotlib installation.

Run from the repo root:  python3 tools/gen_tables.py
The .inc files are committed; this script only needs re-running when we bump the
reference matplotlib version (record the version in the .inc header).
"""

import pathlib

import matplotlib
import matplotlib.colors as mcolors
from matplotlib.markers import MarkerStyle

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "core"

HEADER = (
    "// Generated by tools/gen_tables.py from matplotlib {v} — do not edit.\n".format(
        v=matplotlib.__version__
    )
)


def gen_css4() -> None:
    rows = []
    for name, hexval in sorted(mcolors.CSS4_COLORS.items()):
        h = hexval.lstrip("#")
        rows.append(f'    {{"{name}", 0x{h.upper()}}},')
    body = HEADER + (
        "// clang-format off\n"
        "static constexpr NamedColor kCss4Colors[] = {\n" + "\n".join(rows) + "\n};\n"
        "// clang-format on\n"
    )
    (OUT / "css4_colors.inc").write_text(body)
    print(f"css4_colors.inc: {len(rows)} entries")


def gen_tab_and_base() -> None:
    lines = [HEADER, "// clang-format off"]
    lines.append("static constexpr NamedColor kTabColors[] = {")
    for name, hexval in mcolors.TABLEAU_COLORS.items():  # insertion order == tab10 order
        h = hexval.lstrip("#").upper()
        lines.append(f'    {{"{name}", 0x{h}}},')
    lines.append("};")
    lines.append("static constexpr struct { char c; double r, g, b; } kBaseColors[] = {")
    for c, rgb in mcolors.BASE_COLORS.items():
        r, g, b = (float(x) for x in mcolors.to_rgb(rgb))
        lines.append(f"    {{'{c}', {r!r}, {g!r}, {b!r}}},")
    lines.append("};")
    lines.append("// clang-format on")
    (OUT / "tab_base_colors.inc").write_text("\n".join(lines) + "\n")
    print("tab_base_colors.inc written")


# The full matplotlib string-marker set (v0.2).
MARKERS = [".", ",", "o", "v", "^", "<", ">", "1", "2", "3", "4", "8",
           "s", "p", "P", "*", "h", "H", "+", "x", "X", "D", "d", "|", "_"]


def gen_markers() -> None:
    lines = [HEADER, "// clang-format off"]
    lines.append("// Vertices are in marker units: 1 unit == markersize (pt); the marker's")
    lines.append("// base transform is pre-baked. Draw scale = points_to_pixels(markersize).")
    lines.append("static const MarkerDef kMarkerDefs[] = {")
    for m in MARKERS:
        ms = MarkerStyle(m)
        path = ms.get_path().transformed(ms.get_transform())  # bake base transform
        verts = path.vertices
        codes = path.codes
        if codes is None:
            codes = [1] + [2] * (len(verts) - 1)
        vs = ", ".join(f"{{{x:.10g}, {y:.10g}}}" for x, y in verts)
        cs = ", ".join(str(int(c)) for c in codes)
        filled = "true" if ms.is_filled() else "false"
        lines.append(f'    {{"{m}", {{{vs}}}, {{{cs}}}, {filled}}},')
    lines.append("};")
    lines.append("// clang-format on")
    (OUT / "marker_paths.inc").write_text("\n".join(lines) + "\n")
    print(f"marker_paths.inc: {len(MARKERS)} markers")




# Continuous maps sampled at 256; qualitative maps keep their exact entries.
CONTINUOUS_CMAPS = ["viridis", "plasma", "inferno", "magma", "cividis",
                    "coolwarm", "RdBu", "gray", "jet"]
QUALITATIVE_CMAPS = ["tab10", "tab20"]


def gen_colormaps() -> None:
    import numpy as np

    lines = [HEADER, "// clang-format off"]
    lines.append("// RGB triples packed as 0xRRGGBB; qualitative maps use exact entries,")
    lines.append("// continuous maps are sampled at 256 (matching mpl's default N).")
    lines.append("static const CmapDef kColormaps[] = {")
    for name in CONTINUOUS_CMAPS + QUALITATIVE_CMAPS:
        cmap = matplotlib.colormaps[name]
        qualitative = name in QUALITATIVE_CMAPS
        n = cmap.N if qualitative else 256
        xs = np.arange(n) / max(1, n - 1) if not qualitative else (np.arange(n) + 0.5) / n
        vals = cmap(xs)
        packed = []
        for r, g, b, _a in vals:
            packed.append(f"0x{round(r*255):02X}{round(g*255):02X}{round(b*255):02X}")
        lines.append(f'    {{"{name}", {{{", ".join(packed)}}}, '
                     f'{"true" if qualitative else "false"}}},')
    lines.append("};")
    lines.append("// clang-format on")
    (OUT / "colormap_luts.inc").write_text("\n".join(lines) + "\n")
    print(f"colormap_luts.inc: {len(CONTINUOUS_CMAPS) + len(QUALITATIVE_CMAPS)} maps")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    gen_css4()
    gen_tab_and_base()
    gen_markers()
    gen_colormaps()
