# Embed a binary file as a C++ source defining `unsigned char <symbol>[]` and
# `size_t <symbol>_size`. Runs at configure time; output is cached and only
# rewritten when the input changes.
function(graphlib_embed_resource input output symbol)
    if(EXISTS "${output}" AND "${output}" IS_NEWER_THAN "${input}")
        return()
    endif()
    file(READ "${input}" hex_content HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex_content}")
    # 16 bytes per line keeps the file diffable and editors happy
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" bytes "${bytes}")
    file(WRITE "${output}"
        "// Generated by cmake/EmbedResource.cmake from ${input} — do not edit.\n"
        "#include <cstddef>\n"
        "extern const unsigned char ${symbol}[];\n"
        "extern const std::size_t ${symbol}_size;\n"
        "const unsigned char ${symbol}[] = {\n${bytes}\n};\n"
        "const std::size_t ${symbol}_size = sizeof(${symbol});\n")
endfunction()
