# cmake -P script: assemble the v1.0 conformance report — every gallery figure
# side by side with the matplotlib twin generated by tools/mpl_twins.py.
#
# Expects: -DGALLERY_DIR=... -DMPL_DIR=... -DOUT_HTML=...

file(GLOB ours "${GALLERY_DIR}/*.svg")
list(SORT ours)

set(rows "")
set(missing 0)
foreach(svg IN LISTS ours)
    get_filename_component(fname "${svg}" NAME)
    get_filename_component(stem "${svg}" NAME_WE)
    string(REPLACE "_" " " title "${stem}")
    if(EXISTS "${MPL_DIR}/${fname}")
        string(APPEND rows "<h2>${title}</h2>\n<div class=\"pair\">
<figure><img loading=\"lazy\" src=\"gallery/${fname}\" alt=\"graphlib ${title}\"/><figcaption>graphlib</figcaption></figure>
<figure><img loading=\"lazy\" src=\"conformance/${fname}\" alt=\"matplotlib ${title}\"/><figcaption>matplotlib</figcaption></figure>
</div>\n")
    else()
        math(EXPR missing "${missing} + 1")
        message(STATUS "conformance: no matplotlib twin for ${fname}")
    endif()
endforeach()

set(html "<!DOCTYPE html>
<html lang=\"en\"><head><meta charset=\"utf-8\"/>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>
<title>graphlib conformance report</title>
<link rel=\"stylesheet\" href=\"site.css\"/>
<style>.pair { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; } @media (max-width: 50rem) { .pair { grid-template-columns: 1fr; } }</style>
</head>
<body>
<nav><a href=\"index.html\">graphlib</a> · <a href=\"quickstart.html\">quick start</a> · <a href=\"gallery.html\">gallery</a> · <strong>conformance</strong> · <a href=\"api/index.html\">API</a></nav>
<h1>Conformance report</h1>
<p>Every gallery figure next to the same figure produced by matplotlib (the behavior
spec, generated by <code>tools/mpl_twins.py</code> against matplotlib 3.10). Numeric
behavior — ticks, autoscale limits, colormaps, date labels, path simplification — is
additionally pinned by committed oracle fixtures; deliberate differences are logged in
<a href=\"https://github.com/Nosenzor/graphlib/blob/main/docs/PARITY.md\">PARITY.md</a>.</p>
${rows}
</body></html>
")
file(WRITE "${OUT_HTML}" "${html}")
message(STATUS "conformance.html: ${OUT_HTML}")
